/*  SELECT COUNT(*) FROM Chicago_Crime_Data;  */ -- 1

/* SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME FROM Census_Data
WHERE PER_CAPITA_INCOME < 11000; */ -- 2

/* SELECT CASE_NUMBER FROM Chicago_Crime_Data 
WHERE UPPER(PRIMARY_TYPE) LIKE '%CHILD%' OR UPPER(DESCRIPTION) LIKE '%CHILD%'; */ -- 3

/* SELECT * FROM Chicago_Crime_Data
WHERE PRIMARY_TYPE = 'KIDNAPPING'; */ -- 4

/* SELECT DISTINCT(PRIMARY_TYPE) FROM Chicago_Crime_Data
WHERE UPPER(LOCATION_DESCRIPTION) LIKE '%SCHOOL%'; */ -- 5

/* SELECT ElementaryMiddleorHighSchool, AVG(SAFETY_SCORE) AS SAFETY_SCORE_AVG FROM Chicago_Public_Schools
GROUP BY (ElementaryMiddleorHighSchool); */ -- 6

/* SELECT COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME, PERCENTHOUSEHOLDSBELOWPOVERTY 
FROM Census_Data
ORDER BY PERCENTHOUSEHOLDSBELOWPOVERTY DESC
LIMIT 5; */ -- 7

/* SELECT COMMUNITY_AREA_NUMBER FROM Chicago_Crime_Data
WHERE COMMUNITY_AREA_NUMBER IS NOT NULL
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY COUNT(COMMUNITY_AREA_NUMBER) DESC LIMIT 1; */ -- 8

/* SELECT COMMUNITY_AREA_NAME FROM Census_Data
WHERE HARDSHIP_INDEX = (SELECT MAX(HARDSHIP_INDEX) FROM Census_Data); */ -- 9

/* SELECT MAX(COMMUNITY_AREA_NAME) FROM 
(SELECT COMMUNITY_AREA_NAME FROM Census_Data
 GROUP BY COMMUNITY_AREA_NAME
 ORDER BY COUNT(COMMUNITY_AREA_NAME)); */ -- 10
 
 /* SELECT COUNT(*) FROM Chicago_Public_Schools
 WHERE ElementaryMiddleorHighSchool = 'ES'; */ -- 11
 
/*SELECT COUNT(*) FROM Chicago_Public_Schools
GROUP BY ElementaryMiddleorHighSchool; */ -- 12

/*SELECT * FROM Chicago_Public_Schools
WHERE SAFETY_SCORE = (SELECT MAX(SAFETY_SCORE) FROM Chicago_Public_Schools); */ -- 13

/*UPDATE Chicago_Public_Schools
SET AVERAGE_STUDENT_ATTENDANCE = REPLACE(AVERAGE_STUDENT_ATTENDANCE, '%', ''); */ -- 14

/* SELECT * FROM Chicago_Public_Schools
WHERE AVERAGE_STUDENT_ATTENDANCE < 70; */ -- 15

/* SELECT COMMUNITY_AREA_NAME, SUM(COLLEGE_ENROLLMENT) FROM Chicago_Public_Schools
GROUP BY COMMUNITY_AREA_NAME; */ -- 16

/* SELECT COMMUNITY_AREA_NAME, SUM(COLLEGE_ENROLLMENT) AS TOTAL_ENROLLMENTS FROM Chicago_Public_Schools
GROUP BY COMMUNITY_AREA_NAME
ORDER BY TOTAL_ENROLLMENTS
LIMIT 5; */ -- 17 */ -- 17

/* SELECT ZIPCode, NO_OF_SCHOOLS FROM (SELECT ZIPCode, COUNT(*) AS NO_OF_SCHOOLS FROM Chicago_Public_Schools
GROUP BY ZIPCode)
WHERE NO_OF_SCHOOLS > 5; */ -- 19

/* SELECT HARDSHIP_INDEX FROM Census_Data
WHERE COMMUNITY_AREA_NUMBER = (
	SELECT COMMUNITY_AREA_NUMBER FROM Chicago_Public_Schools
	WHERE COLLEGE_ENROLLMENT = (SELECT MAX(COLLEGE_ENROLLMENT) FROM Chicago_Public_Schools)); */ -- 20
	
/* SELECT * FROM 
	(SELECT PRIMARY_TYPE, COUNT(*) AS NO_OF_CRIMES FROM Chicago_Crime_Data
	GROUP BY PRIMARY_TYPE)
WHERE NO_OF_CRIMES < 10; */ -- 21

/* SELECT * FROM 
	(SELECT PRIMARY_TYPE, COUNT(*) AS NO_OF_CRIMES FROM Chicago_Crime_Data
	GROUP BY PRIMARY_TYPE)
ORDER BY NO_OF_CRIMES
LIMIT 20; */ -- 22
